export const validResult = {
  data: {
    characters: {
      info: {
        pages: 42,
        count: 826,
        next: 2,
        prev: null,
        __typename: "Info",
      },
      results: [
        {
          id: "1",
          name: "Rick Sanchez",
          image: "https://rickandmortyapi.com/api/character/avatar/1.jpeg",
          status: "Alive",
          gender: "Male",
          created: "2017-11-04T18:48:46.250Z",
          species: "Human",
          origin: {
            name: "Earth (C-137)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Citadel of Ricks",
            type: "Space station",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "2",
          name: "Morty Smith",
          image: "https://rickandmortyapi.com/api/character/avatar/2.jpeg",
          status: "Alive",
          gender: "Male",
          created: "2017-11-04T18:50:21.651Z",
          species: "Human",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Citadel of Ricks",
            type: "Space station",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "3",
          name: "Summer Smith",
          image: "https://rickandmortyapi.com/api/character/avatar/3.jpeg",
          status: "Alive",
          gender: "Female",
          created: "2017-11-04T19:09:56.428Z",
          species: "Human",
          origin: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "4",
          name: "Beth Smith",
          image: "https://rickandmortyapi.com/api/character/avatar/4.jpeg",
          status: "Alive",
          gender: "Female",
          created: "2017-11-04T19:22:43.665Z",
          species: "Human",
          origin: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "5",
          name: "Jerry Smith",
          image: "https://rickandmortyapi.com/api/character/avatar/5.jpeg",
          status: "Alive",
          gender: "Male",
          created: "2017-11-04T19:26:56.301Z",
          species: "Human",
          origin: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "6",
          name: "Abadango Cluster Princess",
          image: "https://rickandmortyapi.com/api/character/avatar/6.jpeg",
          status: "Alive",
          gender: "Female",
          created: "2017-11-04T19:50:28.250Z",
          species: "Alien",
          origin: {
            name: "Abadango",
            type: "Cluster",
            __typename: "Location",
          },
          location: {
            name: "Abadango",
            type: "Cluster",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "7",
          name: "Abradolf Lincler",
          image: "https://rickandmortyapi.com/api/character/avatar/7.jpeg",
          status: "unknown",
          gender: "Male",
          created: "2017-11-04T19:59:20.523Z",
          species: "Human",
          origin: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Testicle Monster Dimension",
            type: "Dimension",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "8",
          name: "Adjudicator Rick",
          image: "https://rickandmortyapi.com/api/character/avatar/8.jpeg",
          status: "Dead",
          gender: "Male",
          created: "2017-11-04T20:03:34.737Z",
          species: "Human",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Citadel of Ricks",
            type: "Space station",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "9",
          name: "Agency Director",
          image: "https://rickandmortyapi.com/api/character/avatar/9.jpeg",
          status: "Dead",
          gender: "Male",
          created: "2017-11-04T20:06:54.976Z",
          species: "Human",
          origin: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "10",
          name: "Alan Rails",
          image: "https://rickandmortyapi.com/api/character/avatar/10.jpeg",
          status: "Dead",
          gender: "Male",
          created: "2017-11-04T20:19:09.017Z",
          species: "Human",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Worldender's lair",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "11",
          name: "Albert Einstein",
          image: "https://rickandmortyapi.com/api/character/avatar/11.jpeg",
          status: "Dead",
          gender: "Male",
          created: "2017-11-04T20:20:20.965Z",
          species: "Human",
          origin: {
            name: "Earth (C-137)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "12",
          name: "Alexander",
          image: "https://rickandmortyapi.com/api/character/avatar/12.jpeg",
          status: "Dead",
          gender: "Male",
          created: "2017-11-04T20:32:33.144Z",
          species: "Human",
          origin: {
            name: "Earth (C-137)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Anatomy Park",
            type: "Microverse",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "13",
          name: "Alien Googah",
          image: "https://rickandmortyapi.com/api/character/avatar/13.jpeg",
          status: "unknown",
          gender: "unknown",
          created: "2017-11-04T20:33:30.779Z",
          species: "Alien",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "14",
          name: "Alien Morty",
          image: "https://rickandmortyapi.com/api/character/avatar/14.jpeg",
          status: "unknown",
          gender: "Male",
          created: "2017-11-04T20:51:31.373Z",
          species: "Alien",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Citadel of Ricks",
            type: "Space station",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "15",
          name: "Alien Rick",
          image: "https://rickandmortyapi.com/api/character/avatar/15.jpeg",
          status: "unknown",
          gender: "Male",
          created: "2017-11-04T20:56:13.215Z",
          species: "Alien",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Citadel of Ricks",
            type: "Space station",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "16",
          name: "Amish Cyborg",
          image: "https://rickandmortyapi.com/api/character/avatar/16.jpeg",
          status: "Dead",
          gender: "Male",
          created: "2017-11-04T21:12:45.235Z",
          species: "Alien",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Earth (Replacement Dimension)",
            type: "Planet",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "17",
          name: "Annie",
          image: "https://rickandmortyapi.com/api/character/avatar/17.jpeg",
          status: "Alive",
          gender: "Female",
          created: "2017-11-04T22:21:24.481Z",
          species: "Human",
          origin: {
            name: "Earth (C-137)",
            type: "Planet",
            __typename: "Location",
          },
          location: {
            name: "Anatomy Park",
            type: "Microverse",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "18",
          name: "Antenna Morty",
          image: "https://rickandmortyapi.com/api/character/avatar/18.jpeg",
          status: "Alive",
          gender: "Male",
          created: "2017-11-04T22:25:29.008Z",
          species: "Human",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Citadel of Ricks",
            type: "Space station",
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "19",
          name: "Antenna Rick",
          image: "https://rickandmortyapi.com/api/character/avatar/19.jpeg",
          status: "unknown",
          gender: "Male",
          created: "2017-11-04T22:28:13.756Z",
          species: "Human",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          __typename: "Character",
        },
        {
          id: "20",
          name: "Ants in my Eyes Johnson",
          image: "https://rickandmortyapi.com/api/character/avatar/20.jpeg",
          status: "unknown",
          gender: "Male",
          created: "2017-11-04T22:34:53.659Z",
          species: "Human",
          origin: {
            name: "unknown",
            type: null,
            __typename: "Location",
          },
          location: {
            name: "Interdimensional Cable",
            type: "TV",
            __typename: "Location",
          },
          __typename: "Character",
        },
      ],
      __typename: "Characters",
    },
  },
};
